language: ruby
addons:
  code_climate:
    repo_token: 24e6dca48d8fe9c48a87881625dc9cbcc10aba9ad3760e3fce38c6c4e5b03927
rvm:
- 2.1
- 2.2
- ruby-head
before_install:
- gem install bundle
install:
- bundle install
script:
- bundle exec rspec -r ./spec/spec_helper.rb
